[metadata]
name = "linux"
version = "6.16.9"
release = 1
description = "The Linux kernel"
url = "https://kernel.org/"
license = "GPL-2.0-only"

[dependencies]

[sources]
linux = "https://www.kernel.org/pub/linux/kernel/v6.x/linux-6.16.9.tar.xz"

[build]
script = """
cd linux-6.16.9

make ARCH=arm64 headers
make ARCH=arm64 INSTALL_HDR_PATH="$pkgroot/usr" headers_install
"""

# TODO: kernel, modules, etc.
